// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XYZStore.Services.CouponAPI.Data;

#nullable disable

namespace XYZStore.Services.CouponAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231203022737_AddCouponToDB")]
    partial class AddCouponToDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("XYZStore.Services.CouponAPI.Models.Coupon", b =>
                {
                    b.Property<int>("CouponID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponID"));

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CouponStatus")
                        .HasColumnType("bit");

                    b.Property<double>("CouponValue")
                        .HasColumnType("float");

                    b.Property<DateTime>("ExpiredDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPercentage")
                        .HasColumnType("bit");

                    b.HasKey("CouponID");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            CouponID = 1,
                            CouponCode = "OJOL",
                            CouponStatus = true,
                            CouponValue = 100000.0,
                            ExpiredDate = new DateTime(2023, 12, 3, 9, 27, 37, 607, DateTimeKind.Local).AddTicks(9981),
                            IsPercentage = false
                        },
                        new
                        {
                            CouponID = 2,
                            CouponCode = "GRATISMAKAN",
                            CouponStatus = false,
                            CouponValue = 30000.0,
                            ExpiredDate = new DateTime(2023, 12, 3, 9, 27, 37, 608, DateTimeKind.Local).AddTicks(44),
                            IsPercentage = false
                        },
                        new
                        {
                            CouponID = 3,
                            CouponCode = "MAKANTERUS",
                            CouponStatus = false,
                            CouponValue = 10.0,
                            ExpiredDate = new DateTime(2023, 12, 3, 9, 27, 37, 608, DateTimeKind.Local).AddTicks(69),
                            IsPercentage = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
