// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XYZStore.Services.MerchantAPI.Data;

#nullable disable

namespace XYZStore.Services.MerchantAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231203055432_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("XYZStore.Services.MerchantAPI.Models.Merchant", b =>
                {
                    b.Property<int>("MerchantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MerchantID"));

                    b.Property<string>("MerchantAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MerchantID");

                    b.ToTable("Merchants");

                    b.HasData(
                        new
                        {
                            MerchantID = 1,
                            MerchantAddress = "XXX",
                            MerchantName = "ABC"
                        },
                        new
                        {
                            MerchantID = 2,
                            MerchantAddress = "XXX",
                            MerchantName = "KIN"
                        },
                        new
                        {
                            MerchantID = 3,
                            MerchantAddress = "XXX",
                            MerchantName = "OT"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
